# see als: https://github.com/hjacobs/connexion-example

swagger: '2.0'
info:
  title: S2S API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
basePath: /api
#security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
#  - oauth2: [uid]

# a simple data path:
paths:
  /translate:
    get:
      tags: [Translate, All]
      operationId: server.get_translation
      summary: Get Translation and Data for sentence
      parameters:
        - $ref: '#/parameters/inSentence'
      responses:
        200:
          description: Return Translation and meta data
          schema:
            $ref: '#/definitions/Translation'
  /compare_translation:
    get:
      tags: [Translate, All]
      operationId: server.compare_translation
      summary: Compare Translation and Data for sentences
      parameters:
        - $ref: '#/parameters/inSentence'
        - $ref: '#/parameters/compareSentences'
      responses:
        200:
          description: Return Translations and distances
#          schema:
#            $ref: '#/definitions/Translation'
  /close_words:
    get:
      tags: [Embedding, All]
      operationId: server.get_close_words
      summary: Get the closest words w.r.t word embedding
      parameters:
        - $ref: '#/parameters/inWord'
        - $ref: '#/parameters/loc'
        - $ref: '#/parameters/p_method'
        - $ref: '#/parameters/limit'
      responses:
        200:
          description: Return list of closest words

parameters:
  inSentence:
    name: in
    description: the input sentence
    in: query
    type: string
    default:  "world"
  compareSentences:
    name: compare
    description: list of sentences to compare against
    in: query
    type: array
    required: true
    items:
      type: string
  inWord:
    name: in
    description: the input word
    in: query
    type: string
    default: "hello"
  loc:
    name: loc
    description: location - src or tgt
    in: query
    type: string
    enum:
      - "src"
      - "tgt"
    default: "src"
  limit:
    name: limit
    description: limit of results
    in: query
    type: integer
    default: 100
  p_method:
    name: p_method
    description: projection method to use
    in: query
    type: string
    enum:
      - "mds"
      - "pca"
      - "tsne"
      - "none"
    default: "pca"


# These definitions are only needed for proper documentation
# no functional purpose
definitions:
  Translation:
    type: object
    required:
      - in
      - out
      - attn
    properties:
      in:
        type: string
        description: input sentence
        example: "The sun is yellow ."
      out:
        type: string
        description: translated sentence
        example: "Die Sonne ist gelb ."
      attn:
        type: array
        description: Attention for each output position
        example: [[.1,.2,.13],[.3,.4,.2]]
        items:
          type: integer




#securityDefinitions:
#  oauth2:
#    type: oauth2
#    flow: implicit
#    authorizationUrl: https://example.com/oauth2/dialog
#    scopes:
#      uid: Unique identifier of the user accessing the service.
